k9s:
  liveViewAutoRefresh: true
  refreshRate: 3
  maxConnRetry: 5
  defaultView: pods
  ui:
    skin: catppuccin-macchiato
    headless: false
    crumbsless: false
    reactive: true
    enableMouse: false
    logoless: true
    noIcons: true
    useFullGVRTitle: true
  skipLatestRevCheck: true
  disablePodCounting: false
  imageScans:
    enable: false
  logger:
    tail: 50
    buffer: 4096
    sinceSeconds: -1
    textWrap: false
    showTime: false
  thresholds:
    cpu:
      critical: 90
      warn: 75
    memory:
      critical: 90
      warn: 75
